### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by MrEngineer02** [jcurl/SerialPortStream#23] opened 2017-05-02 18:04 UTC
I had trouble figuring out how to use this library until I found the documentation on the CodePlex project:
[https://serialportstream.codeplex.com/documentation](url)

I see most of those examples have not been copied to the Wiki on this project:
[https://github.com/jcurl/SerialPortStream/wiki](url)

 Is there any way that I could edit the Wiki to copy/paste the documentation from CodePlex?

-David

**Comment by jcurl** [comment] 2017-05-02 19:59
Duplicate of https://github.com/jcurl/SerialPortStream/issues/16

**Comment by MrEngineer02** [comment] 2017-05-03 01:53
Completed copying documentation from CodePlex.  Thanks for letting me contribute!  My apologies for any disorder.  I'm glad I got to "rescue" all the value-able documentation.

You can close this issue.  I don't expect I will need edit access to the wiki any more.

**Comment by jcurl** [comment] 2017-05-03 04:34
Thank you very much for your contribution.

**Closed by jcurl** 2017-05-03 04:34 UTC
